Repository UQcsse3200/2023-studio-2, pull requests merged in 2023-08, with the labels that each got.

#61 Feature/game state
  source/core/src/main/com/csse3200/game/services/GameState.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/services/GameStateTest.java
  source/core/src/test/com/csse3200/game/services/ServiceLocatorTest.java
Labels: Team 3

#63 Feature/ships and extractors
  source/core/assets/images/broken_elixir_collector.png
  source/core/assets/images/elixir_collector.png
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/resources/ProductionComponent.java
  source/core/src/main/com/csse3200/game/components/resources/Resource.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java
  source/core/src/main/com/csse3200/game/rendering/DamageTextureComponent.java
  source/core/src/test/com/csse3200/game/rendering/DamageTextureComponentTest.java
Labels: enhancement, Team 5

#67 Feature/simplify state management
  source/core/src/main/com/csse3200/game/components/resources/ProductionComponent.java
  source/core/src/main/com/csse3200/game/services/GameState.java
  source/core/src/test/com/csse3200/game/services/GameStateTest.java
Labels: Team 3

#79 Feature/game state/observer
  source/core/src/main/com/csse3200/game/components/resources/ProductionComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/GameState.java
  source/core/src/main/com/csse3200/game/services/GameStateInteraction.java
  source/core/src/main/com/csse3200/game/services/GameStateObserver.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/services/ServiceLocatorTest.java
Labels: Team 3

#82 GameStateObserver + GameStateInteraction JUnit Tests + Javadocs
  source/core/src/main/com/csse3200/game/services/GameStateInteraction.java
  source/core/src/main/com/csse3200/game/services/GameStateObserver.java
  source/core/src/test/com/csse3200/game/services/GameStateInteractionTest.java
  source/core/src/test/com/csse3200/game/services/GameStateObserverTest.java
  source/core/src/test/com/csse3200/game/services/ServiceLocatorTest.java
Labels: Team 3

#85 Feature/buildables
  source/core/assets/configs/gates.json
  source/core/assets/configs/walls.json
  source/core/assets/images/dirt_wall.atlas
  source/core/assets/images/dirt_wall.png
  source/core/assets/images/gate_close.png
  source/core/assets/images/gate_open.png
  source/core/assets/images/stone_wall.atlas
  source/core/assets/images/stone_wall.png
  source/core/assets/images/wall.png
  source/core/assets/images/wall2.png
  source/core/assets/vertices/walls.json
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/HealthBarComponent.java
  source/core/src/main/com/csse3200/game/components/ProximityActivationComponent.java
  source/core/src/main/com/csse3200/game/components/joinable/JoinDirection.java
  source/core/src/main/com/csse3200/game/components/joinable/JoinLayer.java
  source/core/src/main/com/csse3200/game/components/joinable/JoinableComponent.java
  source/core/src/main/com/csse3200/game/components/joinable/JoinableComponentShapes.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/buildables/Wall.java
  source/core/src/main/com/csse3200/game/entities/configs/WallConfig.java
  source/core/src/main/com/csse3200/game/physics/components/ColliderComponent.java
  source/core/src/main/com/csse3200/game/rendering/AtlasRenderComponent.java
  source/core/src/main/com/csse3200/game/services/StructurePlacementService.java
Labels: Sprint 1, Team 7

#101 Feature/obstacle minigame merge with main game
  source/core/assets/configs/asteroid.json
  source/core/assets/images/ExtractorMiniGameBackground.png
  source/core/assets/images/LeftShip.png
  source/core/assets/images/RightShip.png
  source/core/assets/images/Ship.png
  source/core/assets/images/Spaceship.png
  source/core/assets/images/fire.png
  source/core/assets/images/obstacle-enemy.png
  source/core/assets/images/wormhole.jpg
  source/core/src/main/com/csse3200/game/areas/EarthGameArea.java
  source/core/src/main/com/csse3200/game/areas/ExtractorMiniGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/ExtractorRepairPartComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/origiPlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ShipFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java
  source/core/src/main/com/csse3200/game/screens/ExtractorMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceMapScreen.java
Labels: help wanted, Team 6

#105 Feature/player
  source/core/assets/images/Player-frame-0.png
  source/core/assets/images/Player-frame-1.png
  source/core/assets/images/Player-frame-3.png
  source/core/assets/images/Player-frame-4.png
  source/core/assets/images/Player-frame-5.png
  source/core/assets/images/Player-frame-6.png
  source/core/assets/images/Player-frame-7.png
  source/core/assets/images/Player-frame-8.png
  source/core/assets/images/playerSS.atlas
  source/core/assets/images/playerSS.png
  source/core/assets/images/playerSS_0.png
  source/core/assets/images/playerSS_1.png
  source/core/assets/images/playerSS_2.png
  source/core/assets/images/playerSS_3.png
  source/core/assets/images/playerSS_4.png
  source/core/assets/images/playerSS_5.png
  source/core/assets/images/playerSS_6.png
  source/core/assets/images/playerSS_7.png
  source/core/assets/images/player_blank.png
  source/core/assets/images/weaponSpriteSheet.png
  source/core/assets/images/wrench.atlas
  source/core/assets/images/wrench.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/EarthGameArea.java
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/components/PowerupComponent.java
  source/core/src/main/com/csse3200/game/components/Weapons/WeaponControllerComponent.java
  source/core/src/main/com/csse3200/game/components/Weapons/WeaponType.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/factories/AttackFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PowerupFactory.java
  source/core/src/main/com/csse3200/game/rendering/AnimationRenderComponent.java
  source/core/src/main/com/csse3200/game/services/EntityPlacementService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/utils/math/Vector2Utils.java
  source/core/src/test/com/csse3200/game/components/PowerupComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/KeyboardPlayerInputComponentTest.java
  source/core/src/test/com/csse3200/game/entities/EntityServiceTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PowerupFactoryTest.java
Labels: Team 4

#113 Feature/planet travel gui
  source/core/src/main/com/csse3200/game/areas/NavigationArea.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/navigation/NavigationPlanetComponent.java
  source/core/src/main/com/csse3200/game/components/navigation/PlanetComponent.java
  source/core/src/main/com/csse3200/game/components/navigation/level3.java
  source/core/src/main/com/csse3200/game/components/navigation/level4.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: Team 3
