Repository UQcsse3200/2023-studio-2, pull requests merged in 2023-09, with the labels that each got.

#179 Feature/space map
  source/core/assets/images/space_navigation_arrow_down.png
  source/core/assets/images/space_navigation_arrow_left.png
  source/core/assets/images/space_navigation_arrow_right.png
  source/core/assets/images/space_navigation_arrow_up.png
  source/core/assets/images/space_navigation_background.png
  source/core/assets/images/space_navigation_background_star_frame_0.png
  source/core/assets/images/space_navigation_background_star_frame_1.png
  source/core/assets/images/space_navigation_background_star_frame_2.png
  source/core/assets/images/space_navigation_background_star_frame_3.png
  source/core/assets/images/space_navigation_background_star_frame_4.png
  source/core/assets/images/space_navigation_background_star_frame_5.png
  source/core/assets/images/space_navigation_background_star_frame_6.png
  source/core/assets/images/space_navigation_background_star_frame_7.png
  source/core/assets/images/space_navigation_planet_0.png
  source/core/assets/images/space_navigation_planet_1.png
  source/core/assets/images/space_navigation_planet_2.png
  source/core/assets/images/space_navigation_planet_3.png
  source/core/assets/images/space_navigation_planet_4.png
  source/core/assets/images/space_navigation_planet_5.png
  source/core/assets/images/space_navigation_planet_6.png
  source/core/assets/images/space_navigation_planet_7.png
  source/core/assets/images/space_navigation_planet_8.png
  source/core/assets/images/space_navigation_title.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/NavigationArea.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/navigation/NavigationPlanetComponent.java
  source/core/src/main/com/csse3200/game/components/navigation/PlanetComponent.java
  source/core/src/main/com/csse3200/game/components/navigation/level3.java
  source/core/src/main/com/csse3200/game/components/navigation/level4.java
  source/core/src/main/com/csse3200/game/components/spacenavigation/NavigationBackground.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceNavigationScreen.java
Labels: Team 3, Sprint 2

#203 Feature/buildables
  source/core/assets/configs/structure_options.json
  source/core/assets/images/Durasteel.png
  source/core/assets/images/Nebulite.png
  source/core/assets/images/durasteel.png
  source/core/assets/images/nebulite.png
  source/core/src/main/com/csse3200/game/areas/EarthGameArea.java
  source/core/src/main/com/csse3200/game/components/structures/CostComponent.java
  source/core/src/main/com/csse3200/game/components/structures/StructureOption.java
  source/core/src/main/com/csse3200/game/components/structures/StructurePicker.java
  source/core/src/main/com/csse3200/game/components/structures/tools/ExtractorTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/PlacementTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/Tool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/TurretTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/WallTool.java
  source/core/src/main/com/csse3200/game/entities/factories/PopupFactory.java
  source/core/src/test/com/csse3200/game/components/structures/CostComponentTest.java
  source/core/src/test/com/csse3200/game/components/structures/JoinableComponentTest.java
  source/core/src/test/com/csse3200/game/components/structures/StructurePickerTest.java
Labels: Team 7, Sprint 2

#205 Feature/space/integration
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/EarthGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/maingame/ReturnToPlanetDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/player/DeathScreenActions.java
  source/core/src/main/com/csse3200/game/components/story/StoryActions.java
  source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceMapScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceNavigationScreen.java
  source/core/src/main/com/csse3200/game/services/GameState.java
  source/core/src/main/com/csse3200/game/services/GameStateInteraction.java
  source/core/src/main/com/csse3200/game/services/GameStateObserver.java
  source/core/src/main/com/csse3200/game/services/PlanetTravel.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/main/com/csse3200/game/ui/AlertBox.java
  source/core/src/main/com/csse3200/game/ui/DialogueBox.java
  source/core/src/main/com/csse3200/game/ui/MainAlertBox.java
  source/core/src/main/com/csse3200/game/ui/terminal/MainGameActionss.java
  source/core/src/test/com/csse3200/game/components/resources/ResourceProductionTest.java
  source/core/src/test/com/csse3200/game/components/upgradetree/UpgradeTreeTest.java
  source/core/src/test/com/csse3200/game/services/PlanetTravelTest.java
  source/core/src/test/com/csse3200/game/story/StoryActionsTest.java
Labels: Team 3, Sprint 2

#211 Feature/minigame/upgrade ship
  source/core/assets/images/stone.png
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/ShopArea.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/ships/ExitShopDisplay.java
  source/core/src/main/com/csse3200/game/components/ships/ShipStatDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/MinigameShipFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/screens/UpgradeShopScreen.java
  source/core/src/main/com/csse3200/game/services/UpgradeShip.java
Labels: Team 3, Sprint 2

#279 Refactor planetscreen
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/components/Companion/CompanionStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/tasks/AdjustedChaseTask.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
Labels: Team 3

#311 Fixed multiple bugs causing excessive thread spawning.
  source/core/src/main/com/csse3200/game/components/ProjectileAttackComponent.java
  source/core/src/main/com/csse3200/game/components/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/resources/PopupComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/AdjustedChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/BossTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RunTask.java
Labels: bug, Team 3, Sprint 3

#321 Feature/story1
  source/core/assets/configs/NPCs.json
  source/core/assets/images/Astro_NPC.atlas
  source/core/assets/images/Astro_NPC.png
  source/core/assets/images/InitialScreenBG.png
  source/core/assets/images/InitialScreenImage.png
  source/core/assets/images/Jail/jail.atlas
  source/core/assets/images/Jail/jail.png
  source/core/assets/images/astronaut_npc.atlas
  source/core/assets/images/astronaut_npc.png
  source/core/assets/images/refinedBackRightShip.png
  source/core/assets/images/refinedBackShip.png
  source/core/assets/levels/earth/main-area/entities.json
  source/core/assets/levels/earth/main-area/main.json
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/areas/mapConfig/AreaEntityConfig.java
  source/core/src/main/com/csse3200/game/components/InitialSequence/InitialScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/AstroAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/JailAnimationController.java
  source/core/src/main/com/csse3200/game/entities/configs/AstroConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/JailConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
Labels: Team 8, Sprint 3

#347 Feature/player
  .vscode/settings.json
  source/core/assets/configs/deathScreen.json
  source/core/assets/configs/lushLevelConfig.json
  source/core/assets/configs/upgradeBench.json
  source/core/assets/configs/weapons.json
  source/core/assets/images/player/bar-fill.png
  source/core/assets/images/player/heart.png
  source/core/assets/images/player/planet-frame.png
  source/core/assets/images/player/statbar.png
  source/core/assets/images/player/widestatbar.png
  source/core/assets/images/space_navigation_planet_0.png
  source/core/assets/images/upgradetree/background.png
  source/core/assets/levels/earth/main-area/entities.json
  source/core/assets/levels/earth/main-area/main.json
  source/core/assets/levels/earth/main-area/player.json
  source/core/assets/levels/frozen/main-area/entities.json
  source/core/assets/levels/frozen/main-area/main.json
  source/core/assets/levels/frozen/main-area/player.json
  source/core/assets/levels/lush/main-area/entities.json
  source/core/assets/levels/lush/main-area/main.json
  source/core/assets/levels/lush/main-area/player.json
  source/core/assets/sounds/PlayerHealthRecharge.mp3
  source/core/assets/sounds/playerBoostRecharge.mp3
  source/core/assets/sounds/playerDeathRespawn.mp3
  source/core/assets/sounds/upgradeTree.mp3
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/areas/mapConfig/AreaEntityConfig.java
  source/core/src/main/com/csse3200/game/areas/mapConfig/GameAreaConfig.java
  source/core/src/main/com/csse3200/game/components/PowerupComponent.java
  source/core/src/main/com/csse3200/game/components/Weapons/WeaponType.java
  source/core/src/main/com/csse3200/game/components/gamearea/PlanetHudDisplay.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/structures/StructureToolPicker.java
  source/core/src/main/com/csse3200/game/components/upgradetree/UpgradeDisplay.java
  source/core/src/main/com/csse3200/game/components/upgradetree/UpgradeNode.java
  source/core/src/main/com/csse3200/game/components/upgradetree/UpgradeTree.java
  source/core/src/main/com/csse3200/game/entities/configs/PlayerConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/PowerupConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/UpgradeBenchConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PowerupFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java
  source/core/src/main/com/csse3200/game/screens/PlayerDeathScreen.java
  source/core/src/test/com/csse3200/game/components/PlayerStatsHealthTest.java
  source/core/src/test/com/csse3200/game/components/PowerupComponentTest.java
  source/core/src/test/com/csse3200/game/components/upgradetree/UpgradeNodeTest.java
  source/core/src/test/com/csse3200/game/components/upgradetree/UpgradeTreeTest.java
  source/desktop/out/production/resources/configs/lushLevelConfig.json
  source/desktop/out/production/resources/configs/upgradeBench.json
  source/desktop/out/production/resources/levels/earth/main-area/entities.json
  source/desktop/out/production/resources/levels/earth/main-area/main.json
  source/desktop/out/production/resources/levels/lush/main-area/entities.json
  source/desktop/out/production/resources/levels/lush/main-area/main.json
Labels: Team 4, Sprint 3

#364 Space
  source/core/assets/images/navigationmap/arrows/arrow_down.png
  source/core/assets/images/navigationmap/arrows/arrow_down_grey.png
  source/core/assets/images/navigationmap/arrows/arrow_left.png
  source/core/assets/images/navigationmap/arrows/arrow_left_grey.png
  source/core/assets/images/navigationmap/arrows/arrow_right.png
  source/core/assets/images/navigationmap/arrows/arrow_right_grey.png
  source/core/assets/images/navigationmap/arrows/arrow_up.png
  source/core/assets/images/navigationmap/arrows/arrow_up_grey.png
  source/core/assets/images/navigationmap/background.png
  source/core/assets/images/navigationmap/planets/earth.png
  source/core/assets/images/navigationmap/planets/glacial_desolation.png
  source/core/assets/images/navigationmap/planets/infernal_challenge.png
  source/core/assets/images/navigationmap/planets/old_planet_images/Verdant Haven-1.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_0.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_1.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_2.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_3.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_4.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_5.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_6.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_7.png
  source/core/assets/images/navigationmap/planets/old_planet_images/space_navigation_planet_8.png
  source/core/assets/images/navigationmap/planets/verdant_oasis.png
  source/core/assets/images/navigationmap/stars/background_star_frame_0.png
  source/core/assets/images/navigationmap/stars/background_star_frame_1.png
  source/core/assets/images/navigationmap/stars/background_star_frame_2.png
  source/core/assets/images/navigationmap/stars/background_star_frame_3.png
  source/core/assets/images/navigationmap/stars/background_star_frame_4.png
  source/core/assets/images/navigationmap/stars/background_star_frame_5.png
  source/core/assets/images/navigationmap/stars/background_star_frame_6.png
  source/core/assets/images/navigationmap/stars/background_star_frame_7.png
  source/core/assets/images/navigationmap/title.png
  source/core/assets/levels/earth/main-area/main.json
  source/core/assets/levels/frozen/main-area/main.json
  source/core/assets/levels/lush/main-area/main.json
  source/core/src/main/com/csse3200/game/areas/mapConfig/GameAreaConfig.java
  source/core/src/main/com/csse3200/game/components/Companion/CompanionDeathScreenActions.java
  source/core/src/main/com/csse3200/game/components/InitialSequence/InitialScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/obstacleMinigame/ObstacleMiniGameActions.java
  source/core/src/main/com/csse3200/game/components/player/DeathScreenActions.java
  source/core/src/main/com/csse3200/game/components/spacenavigation/NavigationBackground.java
  source/core/src/main/com/csse3200/game/components/spacenavigation/StarBackground.java
  source/core/src/main/com/csse3200/game/components/story/StoryActions.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceMapScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceNavigationScreen.java
  source/core/src/main/com/csse3200/game/screens/StoryScreen.java
  source/core/src/main/com/csse3200/game/services/PlanetTravel.java
  source/core/src/main/com/csse3200/game/ui/AlertBox.java
  source/core/src/main/com/csse3200/game/ui/SpaceMiniTransition.java
Labels: Team 3

#376 Feature/action feedback
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/components/player/ActionFeedbackComponent.java
  source/core/src/main/com/csse3200/game/components/player/AlertUIComponent.java
  source/core/src/main/com/csse3200/game/components/player/IAlpha.java
  source/core/src/main/com/csse3200/game/components/structures/StructureToolPicker.java
  source/core/src/main/com/csse3200/game/rendering/ColorDrawable.java
  source/core/src/test/com/csse3200/game/components/player/ActionFeedbackComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/AlertUIComponentTest.java
  source/core/src/test/com/csse3200/game/rendering/ColorDrawableTest.java
Labels: Team 7, Sprint 3

#377 Feature/game sounds
  source/.gitignore
  source/core/src/main/com/csse3200/game/entities/configs/SoundsConfig.java
  source/core/src/test/com/csse3200/game/components/SoundComponentTest.java
Labels: Team 7, Sprint 3
