Repository UQcsse3200/2023-studio-2, pull requests merged in 2023-10, with the labels that each got.

#382 Fix: EntityService Game Crash + other file path bugs
  source/core/src/main/com/csse3200/game/components/PowerUpDisplayHUD.java
  source/core/src/main/com/csse3200/game/components/obstacleMinigame/ObstacleMiniGameActions.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
Labels: Team 3

#389 Feature/particle effects
  source/core/src/main/com/csse3200/game/components/structures/tools/BasicWallTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/GateTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/IntermediateWallTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/PlacementTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/TurretTool.java
  source/saves/savefile.json
Labels: Team 7, Sprint 3

#398 Feature/explosives
  source/core/assets/configs/explosiveBarrel.json
  source/core/assets/configs/landmine.json
  source/core/assets/configs/structure_tools.json
  source/core/assets/configs/weapons.json
  source/core/assets/images/explosives/Landmines_deactive Final.png
  source/core/assets/images/explosives/explosive-barrel.png
  source/core/assets/images/explosives/grenade.png
  source/core/assets/images/explosives/landmine.png
  source/core/assets/images/weapons/grenade.atlas
  source/core/assets/images/weapons/grenade.png
  source/core/assets/kenney-rpg-expansion/kenneyrpg.json
  source/core/assets/kenney-rpg-expansion/mago3.fnt
  source/core/assets/kenney-rpg-expansion/mago3.png
  source/core/assets/levels/earth/main-area/main.json
  source/core/assets/levels/frozen/main-area/main.json
  source/core/assets/levels/lush/main-area/main.json
  source/core/assets/sounds/explosion/grenade.mp3
  source/core/assets/sounds/explosion/landmine.mp3
  source/core/src/main/com/csse3200/game/components/DeathComponent.java
  source/core/src/main/com/csse3200/game/components/ParticleComponent.java
  source/core/src/main/com/csse3200/game/components/ProximityTriggerComponent.java
  source/core/src/main/com/csse3200/game/components/SoundComponent.java
  source/core/src/main/com/csse3200/game/components/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/GrenadeController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/HomingProjectileController.java
  source/core/src/main/com/csse3200/game/components/Weapons/WeaponControllerComponent.java
  source/core/src/main/com/csse3200/game/components/Weapons/WeaponType.java
  source/core/src/main/com/csse3200/game/components/explosives/ExplosiveComponent.java
  source/core/src/main/com/csse3200/game/components/explosives/ExplosiveConfig.java
  source/core/src/main/com/csse3200/game/components/explosives/TimerAction.java
  source/core/src/main/com/csse3200/game/components/flags/EnemyFlag.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/structures/tools/ExplosiveBarrelTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/LandmineTool.java
  source/core/src/main/com/csse3200/game/components/upgradetree/UpgradeDisplay.java
  source/core/src/main/com/csse3200/game/entities/buildables/Gate.java
  source/core/src/main/com/csse3200/game/entities/configs/ExplosiveBarrelConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/ParticleEffectsConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/WeaponConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/AttackFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ExplosivesFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/LandmineConfig.java
  source/core/src/main/com/csse3200/game/input/InputService.java
  source/core/src/main/com/csse3200/game/services/StructurePlacementService.java
  source/core/src/test/com/csse3200/game/components/DeathComponentTest.java
Labels: Team 4, Team 7, Sprint 3

#403 Feature/storyy
  source/core/assets/images/controls-images/Controls.png
  source/core/assets/images/controls-images/on_exit.png
  source/core/assets/images/controls-images/on_exit_hover.png
  source/core/assets/images/npc/astronaut_npc.atlas
  source/core/assets/images/npc/astronaut_npc.png
  source/core/assets/kenney-rpg-expansion/kenneyrpg.atlas
  source/core/assets/kenney-rpg-expansion/kenneyrpg.json
  source/core/assets/kenney-rpg-expansion/treebox.png
  source/core/assets/levels/earth/main-area/entities/astro.json
  source/core/assets/levels/frozen/main-area/entities/astro.json
  source/core/assets/levels/frozen/main-area/entities/botanist.json
  source/core/assets/levels/frozen/main-area/entities/jail.json
  source/core/assets/levels/lush/main-area/entities/astro.json
  source/core/assets/levels/lush/main-area/entities/botanist.json
  source/core/assets/levels/lush/main-area/entities/jail.json
  source/core/assets/levels/lush/main-area/main.json
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/components/FollowComponent.java
  source/core/src/main/com/csse3200/game/components/InitialSequence/InitialScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/InitialSequence/LabelAccessor.java
  source/core/src/main/com/csse3200/game/components/ShipInteractionPopup.java
  source/core/src/main/com/csse3200/game/components/controls/ControlsScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/npc/AstroAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/AstronautAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/FireAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/JailAnimationController.java
  source/core/src/main/com/csse3200/game/entities/configs/AstronautConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/ControlsScreen.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/main/com/csse3200/game/ui/DialogComponent.java
  source/core/src/main/com/csse3200/game/ui/DialogueBox.java
  source/core/src/main/com/csse3200/game/ui/TitleBox.java
  source/core/src/test/com/csse3200/game/DialogueBoxTest.java
  source/core/src/test/com/csse3200/game/components/npc/AstroAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/npc/JailAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/screens/ControlsScreenTest.java
  source/core/src/test/com/csse3200/game/screens/InitialScreenTest.java
  source/saves/savefile.json
Labels: Team 8, Sprint 3

#399 Major feature changes with pathfinding and new boss enemies
  source/Merge_branch_'feature_enemy'_into_map-enemy.patch
  source/Test Results - DebugRendererTest.html
  source/core/assets/configs/enemy.json
  source/core/assets/images/enemy/Chain/chain.atlas
  source/core/assets/images/enemy/RoboMan.atlas
  source/core/assets/images/enemy/RoboMan.png
  source/core/assets/images/enemy/baseEnemyMelee.png
  source/core/assets/images/enemy/base_enemy.atlas
  source/core/assets/images/enemy/guardian/guardian.atlas
  source/core/assets/images/enemy/guardian/guardian.png
  source/core/assets/levels/earth/main-area/entities/companion.json
  source/core/assets/levels/earth/main-area/entities/laboratory.json
  source/core/assets/levels/earth/main-area/entities/spawners.json
  source/core/assets/levels/earth/main-area/main.json
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/mapConfig/GameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/csse3200/game/components/DeathComponent.java
  source/core/src/main/com/csse3200/game/components/PowerupComponent.java
  source/core/src/main/com/csse3200/game/components/enemy/Invisible.java
  source/core/src/main/com/csse3200/game/components/enemy/Jump.java
  source/core/src/main/com/csse3200/game/components/enemy/SprayTask.java
  source/core/src/main/com/csse3200/game/components/enemy/boss/God.java
  source/core/src/main/com/csse3200/game/components/npc/EnemyAnimationController.java
  source/core/src/main/com/csse3200/game/components/npc/PathFinder.java
  source/core/src/main/com/csse3200/game/components/npc/SpawnerComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/BossTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ChaseTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/ShootTask.java
  source/core/src/main/com/csse3200/game/components/tasks/SpawnAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/SpawnTask.java
  source/core/src/main/com/csse3200/game/components/tasks/SpecialAttackTask.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/SpawnerConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ObstacleFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PowerupFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/physics/PhysicsLayer.java
  source/core/src/main/com/csse3200/game/physics/PhysicsUtils.java
  source/core/src/main/com/csse3200/game/rendering/DebugRenderer.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/test/com/csse3200/game/areas/terrain/TerrainComponentTest.java
  source/core/src/test/com/csse3200/game/components/DeathComponentTest.java
  source/core/src/test/com/csse3200/game/components/npc/PathFinderTest.java
  source/core/src/test/com/csse3200/game/components/npc/SpawnerComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/BossTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/ChaseTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MovementTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/RunTaskTest.java
  source/to_create_patch_file.patch
Labels: Team 2, Sprint 3

#396 Feature/obstacle minigame
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/ReturnToPlanetDisplay.java
  source/core/src/main/com/csse3200/game/components/obstacleMinigame/ObstacleMiniGameActions.java
  source/core/src/main/com/csse3200/game/components/ships/ShipActions.java
  source/core/src/main/com/csse3200/game/components/ships/ShipStatDisplay.java
  source/core/src/main/com/csse3200/game/components/ships/SpaceCollideDamageComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/MinigameObjectFactory.java
  source/core/src/main/com/csse3200/game/screens/SpaceMapScreen.java
  source/core/src/main/com/csse3200/game/services/PlanetTravel.java
Labels: Team 6, Sprint 3

#393 Extractor team
  .DS_Store
  source/core/assets/configs/lushLevelConfig.json
  source/core/assets/images/menu/Background_Test1.png
  source/core/assets/images/ship/Ship.png
  source/core/assets/levels/earth/main-area/entities/spawners.json
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuStarBackground.java
  source/core/src/main/com/csse3200/game/components/npc/SpawnerComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
Labels: Team 5, Sprint 3

#408 Feature/player
  source/core/assets/configs/powerups.json
  source/core/assets/configs/weapons.json
  source/core/assets/images/weapons/bees.atlas
  source/core/assets/levels/earth/main-area/entities/powerups.json
  source/core/assets/levels/earth/main-area/main.json
  source/core/src/main/com/csse3200/game/components/DeathComponent.java
  source/core/src/main/com/csse3200/game/components/PowerUpDisplayHUD.java
  source/core/src/main/com/csse3200/game/components/PowerupComponent.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/BoomerangController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/HomingMissileSprayProjectileController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/KillerBeeController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/ProjectileController.java
  source/core/src/main/com/csse3200/game/components/Weapons/WeaponControllerComponent.java
  source/core/src/main/com/csse3200/game/components/player/WeaponComponent.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/factories/AttackFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PowerupFactory.java
  source/core/src/main/com/csse3200/game/services/EntityPlacementService.java
  source/core/src/test/com/csse3200/game/components/PowerupComponentTest.java
  source/core/src/test/com/csse3200/game/entities/factories/PowerupFactoryTest.java
Labels: Team 4, Sprint 3

#410 Feature/tut2
  saves/savefile.json
  source/core/assets/images/npc/Tutnpc.atlas
  source/core/assets/images/npc/Tutnpc.png
  source/core/assets/levels/tutorial/main-area/entities/fissures.json
  source/core/assets/levels/tutorial/main-area/entities/player.json
  source/core/assets/levels/tutorial/main-area/entities/powerups.json
  source/core/assets/levels/tutorial/main-area/entities/spawners.json
  source/core/assets/levels/tutorial/main-area/entities/tutnpc.json
  source/core/assets/levels/tutorial/main-area/main.json
  source/core/assets/map/tutorialmap.tmx
  source/core/assets/map/tutorialmap2 2.tmx
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/KeyboardInputStep1.java
  source/core/src/main/com/csse3200/game/areas/KeyboardInputStep2.java
  source/core/src/main/com/csse3200/game/areas/KeyboardInputTutorialStep.java
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/areas/TutorialGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/TutnpcAnimationController.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/TutnpcConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/main/com/csse3200/game/ui/TitleBox.java
  source/core/src/main/com/csse3200/game/ui/TutorialDialogue.java
Labels: Team 8, Team 7

#433 Added unit tests and made refinements in .json file
  source/core/assets/levels/earth/main_area/entities/astro.json
  source/core/assets/levels/earth/main_area/entities/jail.json
  source/core/assets/levels/glacial_desolation/main_area/entities/astronaut.json
  source/core/assets/levels/glacial_desolation/main_area/main.json
  source/core/assets/levels/tutorial/main-area/main.json
  source/core/src/main/com/csse3200/game/components/npc/AstronautAnimationController.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/test/com/csse3200/game/components/npc/AstronautAnimationControllerTest.java
Labels: Team 8

#457 Save bug fixes
  source/core/src/main/com/csse3200/game/components/SaveableComponent.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceNavigationScreen.java
Labels: Team 3, Sprint 4

#460 Refactored codebase to use single implementation of StarBackground
  source/core/src/main/com/csse3200/game/components/backgrounds/StarBackground.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuStarBackground.java
  source/core/src/main/com/csse3200/game/components/spacenavigation/NavigationBackground.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/test/com/csse3200/game/components/StarBackgroundTest.java
Labels: Team 3, Sprint 4

#483 Bug Fixes: Screen change game crash + Player reference update
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
Labels: bug, Team 3

#495 Extractor team
  source/core/assets/images/menu/main-menu.png
  source/core/assets/images/menu/settings-image1.png
  source/core/assets/images/navigationmap/arrows/verdant_oasis_refined.png
  source/core/assets/images/navigationmap/planets/blazes_refuge.png
  source/core/assets/images/navigationmap/planets/cryoheim.png
  source/core/assets/images/navigationmap/planets/earth.png
  source/core/assets/images/navigationmap/planets/flora_haven.png
  source/core/assets/images/npc/Astro_NPC.atlas
  source/core/assets/map/Cyan Flower.png
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuStarBackground.java
  source/core/src/main/com/csse3200/game/components/player/PlayerAnimationController.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsStarBackground.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
Labels: Sprint 4

#496 Unified hotbar system for Weapons and Tools
  source/core/assets/configs/structure_tools.json
  source/core/src/main/com/csse3200/game/components/InteractLabel.java
  source/core/src/main/com/csse3200/game/components/player/InventoryComponent.java
  source/core/src/main/com/csse3200/game/components/player/InventoryDisplayComponent.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/structures/StructureToolPicker.java
  source/core/src/main/com/csse3200/game/components/structures/ToolConfig.java
  source/core/src/main/com/csse3200/game/components/structures/tools/AdvTurretTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/BasicWallTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/ExplosiveBarrelTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/ExtractorTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/GateTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/HealTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/IntermediateWallTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/LandmineTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/PlacementTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/ReplacementTool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/Tool.java
  source/core/src/main/com/csse3200/game/components/structures/tools/TurretTool.java
  source/core/src/main/com/csse3200/game/components/upgradetree/UpgradeDisplay.java
  source/core/src/main/com/csse3200/game/components/upgradetree/UpgradeTree.java
  source/core/src/test/com/csse3200/game/components/player/InventoryDisplayComponentTest.java
  source/core/src/test/com/csse3200/game/components/player/PlayerActionsTest.java
  source/core/src/test/com/csse3200/game/components/structures/StructureToolPickerTest.java
  source/core/src/test/com/csse3200/game/components/structures/ToolsConfigTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/BasicWallToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/ExplosiveBarrelToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/ExtractorToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/GateToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/HealToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/IntermediateWallToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/LandmineToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/PlacementToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/ToolTest.java
  source/core/src/test/com/csse3200/game/components/structures/tools/TurretToolTest.java
  source/core/src/test/com/csse3200/game/components/upgradetree/UpgradeTreeTest.java
Labels: Team 4, Team 7, Collaboration Ticket, Sprint 4

#497 Extractor effects
  source/core/assets/levels/global_assets.json
  source/core/assets/particle-effects/extractor/dust.png
  source/core/assets/particle-effects/extractor/extractor_rubble_durasteel.effect
  source/core/assets/particle-effects/extractor/extractor_rubble_nebulite.effect
  source/core/assets/particle-effects/extractor/extractor_rubble_solstite.effect
  source/core/assets/particle-effects/extractor/rubble.png
  source/core/assets/particle-effects/extractor/rubble_2.png
  source/core/assets/particle-effects/extractor/rubble_3.png
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/components/ParticleComponent.java
  source/core/src/main/com/csse3200/game/components/structures/ExtractorAnimationController.java
  source/core/src/main/com/csse3200/game/entities/buildables/Extractor.java
  source/core/src/main/com/csse3200/game/entities/configs/ExtractorConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java
  source/core/src/test/com/csse3200/game/components/ParticleComponentTest.java
Labels: Team 5, Team 7, Collaboration Ticket, Sprint 4

#502 Fixed malformed Extractor configs for later levels.
  source/core/assets/levels/cryoheim/main_area/entities/extractors.json
  source/core/assets/levels/flora_haven/main_area/entities/extractors.json
  source/core/assets/levels/flora_haven/main_area/entities/ship.json
Labels: bug, Team 7

#519 Bug Fixes + Space
  source/core/assets/levels/blazes_refuge/level.json
  source/core/src/main/com/csse3200/game/components/ShipInteractionPopup.java
  source/core/src/main/com/csse3200/game/entities/EntityService.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/main/com/csse3200/game/screens/PlayerDeathScreen.java
  source/core/src/main/com/csse3200/game/services/GameState.java
  source/core/src/main/com/csse3200/game/services/GameStateObserver.java
  source/core/src/main/com/csse3200/game/services/PlanetTravel.java
Labels: Team 3, Sprint 4

#514 Code smells
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/areas/TutorialGameArea.java
  source/core/src/main/com/csse3200/game/areas/mapConfig/LevelConfig.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/DeathComponent.java
  source/core/src/main/com/csse3200/game/components/EnvironmentStatsComponent.java
  source/core/src/main/com/csse3200/game/components/FOVComponent.java
  source/core/src/main/com/csse3200/game/components/ItemPickupComponent.java
  source/core/src/main/com/csse3200/game/components/PowerUpDisplayHUD.java
  source/core/src/main/com/csse3200/game/components/PowerupComponent.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/BoomerangController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/GrenadeController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/NukeController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/Projectile/HomingProjectileController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/Projectile/KillerBeeController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/StaticController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/Swing/LaserSwordSwingController.java
  source/core/src/main/com/csse3200/game/components/Weapons/SpecWeapon/Swing/MeleeSwingController.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionActions.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionAnimationController.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionDeathScreenActions.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionDeathScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionInGameAlerts.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionInteractionControllerComponent.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionInventoryComponent.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionInventoryDisplay.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/companion/CompanionWeaponComponent.java
  source/core/src/main/com/csse3200/game/components/companion/KeyboardCompanionInputComponent.java
  source/core/src/main/com/csse3200/game/components/companion/TouchCompanionInputComponent.java
  source/core/src/main/com/csse3200/game/components/companionweapons/CompanionWeaponController.java
  source/core/src/main/com/csse3200/game/components/companionweapons/CompanionWeaponTargetComponent.java
  source/core/src/main/com/csse3200/game/components/companionweapons/CompanionWeaponType.java
  source/core/src/main/com/csse3200/game/components/initialsequence/InitialScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/initialsequence/LabelAccessor.java
  source/core/src/main/com/csse3200/game/components/minidisplay/MiniScreenDisplay.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/ships/ShipAnimationController.java
  source/core/src/main/com/csse3200/game/components/ships/ShipUpgradesComponent.java
  source/core/src/main/com/csse3200/game/components/ships/SpaceCollideDamageComponent.java
  source/core/src/main/com/csse3200/game/components/structures/CostComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/CompanionWeaponConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/CompanionWeaponConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/CompanionAttackFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/CompanionFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/CompanionWeaponFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ShipUpgradesFactory.java
  source/core/src/main/com/csse3200/game/input/KeyboardInputFactory.java
  source/core/src/main/com/csse3200/game/input/TouchInputFactory.java
  source/core/src/main/com/csse3200/game/screens/CompanionDeathScreen.java
  source/core/src/main/com/csse3200/game/screens/InitialScreen.java
  source/core/src/main/com/csse3200/game/screens/MiniScreen.java
  source/core/src/test/com/csse3200/game/components/PowerupComponentTest.java
  source/core/src/test/com/csse3200/game/components/companion/CompanionAnimationControllerTest.java
  source/core/src/test/com/csse3200/game/components/companion/CompanionStatsDisplayTest.java
  source/core/src/test/com/csse3200/game/components/companionweapons/CompanionWeaponControllerTest.java
  source/core/src/test/com/csse3200/game/services/GameStateObserverTest.java
Labels: Team 3, Sprint 4

#521 Feature/obstacle minigame
  source/core/assets/images/minigame/bang.png
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/components/maingame/ReturnToPlanetDisplay.java
  source/core/src/main/com/csse3200/game/components/obstacleMinigame/ObstacleMiniGameActions.java
  source/core/src/main/com/csse3200/game/entities/factories/StructureFactory.java
  source/core/src/main/com/csse3200/game/input/FireInputComponent.java
  source/core/src/main/com/csse3200/game/input/HoleInputComponent.java
  source/core/src/main/com/csse3200/game/screens/ExtractorMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceMapScreen.java
  source/core/src/main/com/csse3200/game/windows/ExtractorMinigameWindow.java
  source/core/src/test/com/csse3200/game/ExtractorWindowTest.java
  source/core/src/test/com/csse3200/game/areas/ExtractorGameAreaTest.java
  source/core/src/test/com/csse3200/game/components/obstacleMinigame/ObstacleMiniGameActionsTest.java
  source/core/src/test/com/csse3200/game/components/ships/ShipActionsTest.java
  source/core/src/test/com/csse3200/game/entities/factories/MinigameObjectFactoryTest.java
  source/core/src/test/com/csse3200/game/entities/factories/MinigameShipFactoryTest.java
  source/core/src/test/com/csse3200/game/input/ExtinguisherInputComponentTest.java
  source/core/src/test/com/csse3200/game/input/FireInputComponentTest.java
  source/core/src/test/com/csse3200/game/input/HoleInputComponentTest.java
  source/core/src/test/com/csse3200/game/input/SpannerInputComponentTest.java
  source/core/src/test/com/csse3200/game/screens/ExtractorScreenTest.java
Labels: Sprint 4

#542 Extractor team
  source/core/src/main/com/csse3200/game/components/companion/CompanionStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuStarBackground.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsStarBackground.java
Labels: Team 5, approved, Sprint 4

#544 Feature/tut2
  source/core/assets/configs/companion.json
  source/core/assets/images/npc/Tutnpc.atlas
  source/core/assets/images/npc/Tutnpc.png
  source/core/assets/images/npc/Tutorial_NPC.atlas
  source/core/assets/images/npc/Tutorial_NPC.png
  source/core/assets/levels/global_assets.json
  source/core/assets/levels/tutorial/main_area/main.json
  source/core/src/main/com/csse3200/game/components/npc/TutnpcAnimationController.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/ControlsScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
Labels: Team 8, Sprint 4

#566 Feature/buildables
  source/core/src/main/com/csse3200/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/csse3200/game/ai/tasks/DefaultTask.java
  source/core/src/main/com/csse3200/game/areas/ControlGameArea.java
  source/core/src/main/com/csse3200/game/areas/ExtractorMiniGameArea.java
  source/core/src/main/com/csse3200/game/areas/map_config/AreaEntityConfig.java
  source/core/src/main/com/csse3200/game/areas/map_config/GameAreaConfig.java
  source/core/src/main/com/csse3200/game/areas/map_config/GameConfig.java
  source/core/src/main/com/csse3200/game/areas/map_config/ResourceCondition.java
  source/core/src/main/com/csse3200/game/components/player/KeyboardPlayerInputComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerActions.java
  source/core/src/main/com/csse3200/game/components/structures/StructureToolPicker.java
Labels: Team 7, Sprint 4

#569 Game Crash Bug
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
Labels: bug

#568 Feature/obstacle minigame
  source/core/assets/images/minigame/extractor.png
  source/core/assets/levels/obstacleGameAssets.json
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/map_config/MiniGameAssetsConfig.java
  source/core/src/main/com/csse3200/game/components/gamearea/PerformanceDisplay.java
  source/core/src/main/com/csse3200/game/components/ships/DistanceDisplay.java
  source/core/src/main/com/csse3200/game/components/ships/ShipActions.java
  source/core/src/main/com/csse3200/game/components/ships/ShipStatDisplay.java
  source/core/src/main/com/csse3200/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/csse3200/game/screens/BrickBreakerScreen.java
  source/core/src/main/com/csse3200/game/screens/ExtractorMiniGameScreen.java
  source/core/src/main/com/csse3200/game/screens/SpaceMapScreen.java
  source/core/src/main/com/csse3200/game/windows/ExtractorMinigameWindow.java
  source/core/src/test/com/csse3200/game/areas/SpaceGameAreaTest.java
Labels: bug, Team 6, Sprint 4

#580 Feature/tut2
  source/core/assets/configs/circle.json
  source/core/assets/images/npc/circle.png
  source/core/assets/images/npc/panel.png
  source/core/assets/levels/global_assets.json
  source/core/assets/levels/tutorial/main_area/entities/circle.json
  source/core/assets/levels/tutorial/main_area/main.json
  source/core/src/main/com/csse3200/game/areas/MapGameArea.java
  source/core/src/main/com/csse3200/game/entities/configs/CircleConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/screens/PlanetScreen.java
  source/core/src/main/com/csse3200/game/screens/TutorialScreen.java
  source/core/src/main/com/csse3200/game/ui/TutorialDialogue.java
  source/core/src/main/com/csse3200/game/windows/PauseWindow.java
Labels: Team 8, Sprint 4

#588 Feature/obstacle minigame bug fixes
  source/core/assets/kenney-rpg-expansion/kenneyrpg.json
  source/core/assets/levels/blazes_refuge/main_area/entities/circle.json
  source/core/assets/levels/cryoheim/main_area/entities/fissures.json
  source/core/assets/levels/earth/main_area/entities/astro.json
  source/core/assets/levels/earth/main_area/entities/portals.json
  source/core/assets/levels/flora_haven/main_area/entities/fissures.json
  source/core/src/main/com/csse3200/game/areas/SpaceGameArea.java
  source/core/src/main/com/csse3200/game/areas/map_config/MiniGameAssetsConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/CompanionFactory.java
  source/core/src/test/com/csse3200/game/areas/SpaceGameAreaTest.java
Labels: bug
